#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python=$(which python3)

if [ ! -d "venv" ]; then
    # For error 'executable `python` not found' run
    # rm -Rf ~/.local/share/virtualenv
    ${python} -m venv ./venv
    source ./venv/bin/activate
    python="${ROOT}/venv/bin/python3"
else
    ${python} -m venv ./venv
fi

pip="${python} -m pip"

${pip} install --upgrade pip

${pip} install --requirement requirements-dev.txt

pre-commit install